name: docker setup and pull 

on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout 
        uses: actions/checkout@v2

#       - name: Set up Docker Buildx
#         uses: docker/setup-buildx-action@v1
        
#       - name: pull a docker image
#         run: |
#           docker pull hello-world
#           docker images

      - name: login to registry.cloud-tools.datastax.com
        run: |
           echo '${{ secrets.DOCKER_CFG }}' > ~/.docker/config.json
           cat  ~/.docker/config.json
           docker login registry.cloud-tools.datastax.com 
