# This is a basic workflow to help you get started with Actions

name: Hello-world test basic GH env

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Dump all GH default varaibles
        run: | 
          cat ${GITHUB_ENV}
          env
          
          echo ""
          echo "-----------------------------------------------------------------------------"
          
          if [[ ${GITHUB_EVENT_NAME} == "push" ]]; then
            BRF_BRANCH=${GITHUB_REF_NAME}
          elif [[ ${GITHUB_EVENT_NAME} == "pull_request" ]]; then 
            BRF_BRANCH=${GITHUB_HEAD_REF} 
          fi
          
          BRF_REPO=${GITHUB_REPOSITORY##*/}
          echo "BRF_REPO is [${BRF_REPO}]"
          echo "BRF_BRANCH is [${BRF_BRANCH}]"
          echo "GITHUB_EVENT_NAME is [${GITHUB_EVENT_NAME}]"
          echo "GITHUB_HEAD_REF is [${GITHUB_HEAD_REF}]"
          echo "GITHUB_BASE_REFis [${GITHUB_BASE_REF}]"
          echo ""
          echo ""

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
