# This is a basic workflow that is manually triggered

name: Manual workflow

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "greet"
  greet:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Runs a single command using the runners shell
    - name: print env     
      run: |
        env

        echo "--------------------------------------------------------------"  
        REAL_BRANCH=${GITHUB_REF_NAME}
        echo "--------------------------------------------------------------"  
        echo "REAL_BRANCH is [${REAL_BRANCH}]"
        if [[ ${GITHUB_EVENT_NAME} == "push" ]]; then
          REAL_BRANCH=${GITHUB_REF_NAME}
        elif [[ ${GITHUB_EVENT_NAME} == "pull_request" ]]; then 
          REAL_BRANCH=${GITHUB_HEAD_REF} 
        fi
        echo "GITHUB_EVENT_NAME is [${GITHUB_EVENT_NAME}]"
        echo "GITHUB_REF_NAME is [${GITHUB_REF_NAME}]"
        echo "GITHUB_HEAD_REF is [${GITHUB_HEAD_REF}]"
        echo "REAL_BRANCH is [${REAL_BRANCH}]"
