on:
  pull_request_target:
    types:
      - closed
    branches:    
      - main
  workflow_dispatch:    
  
jobs:
  my_job:
    runs-on: ubuntu-latest
    steps:
      - name: Git checkout
        uses: actions/checkout@v2
        
      - name: dump env
        run: |
          env
          echo "-----------------"
          echo $GITHUB_REF_NAME
          echo "-----------------"
