on:
  pull_request:
    types:
      - closed
    branches:    
      - main
  workflow_dispatch:    
  
jobs:
  my_job:
    runs-on: ubuntu-latest
    steps:
      - name: Git checkout
        uses: actions/checkout@v2
        
      - name: dump env
        run: |
          env
          
          REAL_BRANCH=${GITHUB_REF_NAME}
          if [[ ${GITHUB_EVENT_NAME} == "pull_request" ]]; then 
            REAL_BRANCH=${GITHUB_HEAD_REF} 
          fi
          echo "-----------------"
          echo $REAL_BRANCH
          echo "-----------------"
