name: nested matrix
env: 
  BATCH_SIZE: 2  
on: 
  workflow_dispatch:

jobs:
  generate-matrix:
    runs-on: ubuntu-latest
    steps:
      - name: Git checkout
        uses: actions/checkout@v3

      - name: generate matrix
        run: |
          clusters=($(find test-dirs  -type d -maxdepth 2 -mindepth 2 | sort))
          echo ### $clusters ###

  build:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        ddata: [ [1, 2], [a, b] ]
#        ddata: [ 1, a ]
    
    steps:
      - name: check matrix content ${{ join(matrix.ddata, ' ') }}
        run: |
          myArray=( ${{  join(matrix.ddata, ' ') }} )
          for str in ${myArray[@]}; do
            echo $str
          done

