name: nested matrix
on: 
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        ddata: [ [1, 2], [a, b] ]
#        ddata: [ 1, a ]
    
    steps:
      - name: check matrix content ${{ join(matrix.ddata, ' ') }}
        run: |
          myArray=( ${{  join(matrix.ddata, ' ') }} )
          for str in ${myArray[@]}; do
            echo $str
          done

